language: java
sudo: required
jdk:
- openjdk8
addons:
  sonarcloud:
    organization: "vatbub-github"
cache:
  directories:
  - "$HOME/.m2"
install:
- wget https://s3.eu-central-1.amazonaws.com/vatbubjdk/jdk-8u191-linux-x64.tar.gz -nv
- tar -xf jdk-8u191-linux-x64.tar.gz
- export JAVA_HOME=/home/travis/build/vatbub/javametricscatcher/jdk1.8.0_191/
script:
- mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar --settings travisMavenSettings.xml
#before_cache:
#- mvn dependency:copy -Dartifact=com.github.vatbub:awsEc2InstanceRebooter:1.0:jar:jar-with-dependencies
#- java -jar target/dependency/awsEc2InstanceRebooter-1.0-jar-with-dependencies.jar -c reboot -r EU_CENTRAL_1 -k $awsKey -s $awsSecret -i $awsInstanceId
after_failure:
  - cat javametricscatchercommon/target/surefire-reports/*.txt
  - cat javametricscatcherclient/target/surefire-reports/*.txt
  - cat javametricscatcherserver/target/surefire-reports/*.txt
after_success:
- source ./travisAfterSuccess.sh
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - vatbub123+travisbuildnotification@googlemail.com
    on_success: never
    on_failure: always
before_install:
  - openssl aes-256-cbc -K $encrypted_46fd01dcc5b9_key -iv $encrypted_46fd01dcc5b9_iv -in github_deploy_key.enc -out github_deploy_key -d
